config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :sessions
  resources :resources do
    resources :comments
  end
  resources :comments do
    resources :resources
    resources :users
end
  root 'resources#index'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :resource
  belongs_to :user 
end

app/models/resource.rb
class Resource < ActiveRecord::Base

  belongs_to :user
  has_many :comments,  dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :resources, dependent: :destroy
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user


  def authorize
    redirect_to '/login' unless current_user
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:edit, :update, :destroy]

  def index
    @comments = Comment.all
  end

  def show
  end

  def new
    @comment = Comment.new
  end

  def edit
  end

  def create
    # @resource = Resource.find(params[:resource_id])
    @comment = Comment.create(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      redirect_to :back
    else
      flash.now[:danger] = "error"
    end
  #API BS HERE
  end

  def update
  end

  def destroy
    @comment.destroy
  end

  private
  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:comment, :content, :resource_id, :user_id)
  end
end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController

  before_filter :authorize

  def index
    @resources = Resource.all
  end

  def new
    @resource = Resource.new
  end

  def create
    @resource = Resource.create(resource_params)
    redirect_to resources_path
  end

  def edit
    @resource = Resource.find(params[:id])
  end

  def show
    @resource = Resource.find(params[:id])
    @comment = Comment.new      # Added by Ed
  end

  def update
    @resource = Resource.find(params[:id])
    @resource.update(resource_params)
    redirect_to (resource_path(@resource))
  end

  def destroy
    @resource = Resource.find(params[:id])
    @resource.destroy
    redirect_to resources_path
  end

  private

  def resource_params
    params.require(:resource).permit(:title, :url, :description)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    # If the User exists and the passsword entered is correct.
    if user && user.authenticate(params[:password])
      # Save the user id inside the browser cookie.
      # This is how we keep the user logged in when they are navigating around the website.
      session[:user_id] = user.id
      redirect_to'/'
    else
      # If users login doesnt work send them back to the login form.
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  # Actions for Bcrypt
  def new
    user = User.new
  end

  # createas a new user,stores session ID to user.
  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end

private


  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= simple_form_for @comment do |f| %>
  <%= f.input :content %>
  <%= f.hidden_field(:user_id) %> <!-- added -->
  <%= f.hidden_field(:resource_id, value: @resource.id) %> <!-- added -->
  <%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WynSources</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <!-- Login Shit -->
  <% if current_user %>
    Signed in as: <%= current_user.name %> | <%= link_to "Logout", '/logout' %>
    <div class="newBut"><%= link_to 'New', '/resources/new' %></div>
  <% else %>
    <%= link_to "Login", '/login' %> | <%= link_to 'Signup', '/signup' %>
  <% end %>

<%= yield %>

</body>
</html>

app/views/resources/edit.html.erb
<%= simple_form_for @resource do |f| %>
  <%= f.input :title %>
  <%= f.input :url %>
  <%= f.input :description %>
  <%= f.button :submit %>
<% end %>


<%= link_to 'Back', '/resources' %>

app/views/resources/index.html.erb
<h1>Resources</h1>

<% @resources.each do |r| %>
<ul>
  <li><%= link_to r.title, resource_path(r)%></li>
  <li><a href="<%= r.url %>"><%= r.url %></a></li>
  <li><%= link_to 'Edit', edit_resource_path(r) %></li>
  <li><%= link_to 'View', resource_path(r) %></li>
  <li><%= link_to 'Delete', resource_path(r), method: :delete, data: { confirm: "Are you sure you would like to delete this Resource?"} %></li>
</ul>
<% end %>

app/views/resources/new.html.erb
<h1>Add a Resource!!@</h1>

<%= simple_form_for @resource do |f| %>
  <%= f.input :title %>
  <%= f.input :url %>
  <%= f.input :description %>
  <%= f.button :submit %>
<% end %>


<%= link_to 'Back', '/resources' %>

app/views/resources/show.html.erb
<h2>showed</h2>

<ul>
  <li><%= @resource.title %></li>
  <li><%= link_to @resource.url, @resource.url%></li>
  <li><%= @resource.description %></li>
</ul>

<p>Comments:</p>

<% @resource.comments.each do |com| %>
  <p>
    <%= com.content %>
    Added <%= time_ago_in_words com.created_at %> ago
  </p>
<% end %>

<%= render 'comments/form' %>

<%= link_to 'Back', '/resources' %>

app/views/users/index.html.erb
<h1>FUck yeah!</h1>


<%= link_to 'Resources', '/resources' %>

app/views/users/new.html.erb
<h1>Signup!</h1>


  <%= form_for :user, url: '/users' do |f| %>
    Name: <br><%= f.text_field :name %><br>
    Email: <br> <%=  f.text_field :email %><br>
    Password: <br><%= f.password_field :password %><br>
    Password Confirmation: <br><%= f.password_field :password_confirmation %><br><br>
    <%= f.submit 'Submit' %>
  <% end %>

app/views/users/show.html.erb
<h2>show</h2>